### ISSUE TITLE
Wrong version of docker image

### ISSUE THREAD

**Issue by labrcat** [intersystems-ib/workshop-rest-iam#3]
In the README.md the version of IRIS docker image is wrong. If you execute this command:
>docker pull containers.intersystems.com/intersystems/iris:2021.1.0.205.0

The result is this error:
>Error response from daemon: manifest for containers.intersystems.com/intersystems/iris:2021.1.0.205.0 not found: manifest unknown: The named manifest is not known to the registry.

I searched  in official documentation in this portal:
https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=PAGE_CONTAINERREGISTRY

I founded that the version in documentation is:
iris:2021.1.0.2**0**5.0 --> iris:2021.1.0.2**1**5.0

If we execute the command with the version changed works:
>docker pull containers.intersystems.com/intersystems/iris:2021.1.0.215.0
2021.1.0.215.0: Pulling from intersystems/iris
f22ccc0b8772: Already exists
3cf8fb62ba5f: Already exists
e80c964ece6a: Already exists
a6af04964d94: Already exists
47f826e0963d: Pull complete
9e204304aa33: Pull complete
87b1d5e2948f: Pull complete
02e1a1a5b770: Pull complete
1f78e9e987a0: Pull complete
Digest: sha256:524fff189776e726fa349eba5fcf45a4a6fc491d355c3121c238b1230ef5624a
Status: Downloaded newer image for containers.intersystems.com/intersystems/iris:2021.1.0.215.0
containers.intersystems.com/intersystems/iris:2021.1.0.215.0

Also we changed the reference of version in Dockerfile.

**Comment by albertoft** [comment]
Fixed!
